type Scope =
  | "frontend"
  | "backend"
  | "devops"
  | "design"
  | "management"
  | "other";

export const SENTENCES: Record<Scope | "general", string[]> = {
  frontend: [
    "The shadow DOM recursively rehydrated the virtual nodes during server-side rendering",
    "The webpack bundle optimization quantum-compressed the JavaScript heap",
    "The CSS-in-JS framework recursively inherited from its own styled components",
    "The micro-frontend architecture fractalized into autonomous feature modules",
    "The progressive web app transcended its service worker limitations",
    "The reactive state management system achieved quantum entanglement with the view layer",
    "The component lifecycle hooks entered an infinite render loop in the virtual DOM",
    "The CSS grid imploded into a non-euclidean layout structure",
    "The client-side routing engine deconstructed the URL parameter matrix",
    "The JavaScript runtime garbage collector achieved sentience during heap optimization",
    "The web components shadowRoot negotiated a peace treaty with the light DOM",
    "The accessibility tree recursively vocalized its own ARIA attributes",
    "The single-page application achieved time travel through the router history API",
    "The responsive breakpoints achieved quantum superposition across viewport dimensions",
    "The browser rendering engine fork-bombed the repaint cycle",
    "The frontend build pipeline recursively transpiled its own source maps",
    "The React hooks ecosystem achieved recursive component composition",
    "The CSS custom properties mutated during cascade resolution",
    "The event propagation bubble achieved escape velocity in the DOM tree",
    "The type definitions recursively implemented their own interfaces",
    "The module bundler achieved circular dependency enlightenment",
    "The state management store dispatched actions to alternate timelines",
    "The CSS-in-JS runtime achieved zero-latency style injection",
    "The component library documentation self-generated its own examples",
    "The frontend testing framework achieved deterministic chaos simulation",
    "The web assembly module compiled the compiler that compiled it",
    "The browser developer tools inspected their own implementation",
    "The TypeScript compiler type-checked its own type definitions",
    "The CSS preprocessor achieved recursive mixin expansion",
    "The frontend performance metrics benchmarked their own measurements",
    "The UI component hierarchy achieved recursive prop drilling",
    "The client-side form validation rules validated themselves",
    "The animation framework interpolated between impossible states",
    "The frontend security middleware encrypted its own encryption keys",
    "The progressive enhancement layer transcended browser compatibility",
    "The accessibility focus trap captured the screen reader itself",
    "The frontend internationalization system translated its own translations",
    "The client-side storage quota exceeded quantum storage limits",
    "The frontend error boundary contained an uncontainable error",
    "The responsive image srcset achieved infinite resolution scaling",
    "The frontend cache invalidated its own cache invalidation strategy",
    "The CSS custom property registry registered its own registrations",
    "The frontend routing system mapped impossible paths to possible states",
    "The web socket connection multiplexed its own protocol upgrades",
    "The frontend build artifacts recursively optimized their own size",
    "The component style system achieved quantum style encapsulation",
    "The frontend testing suite tested its own test coverage",
    "The client-side validation schema validated its own validation rules",
    "The frontend monitoring system monitored its own monitoring status",
    "The web platform APIs polyfilled their own implementations",
  ],
  backend: [
    "The microservice mesh achieved recursive service discovery enlightenment",
    "The distributed database sharded its own sharding strategy",
    "The event sourcing system journaled its own journal entries",
    "The API gateway quantum-encrypted its own encryption protocols",
    "The message broker achieved infinite message queue recursion",
    "The GraphQL resolver tree collapsed into a gravitational singularity",
    "The backend validation pipeline validated its own validation rules",
    "The caching layer cached its own cache invalidation strategy",
    "The authentication service authenticated its own authentication tokens",
    "The database indexing system achieved recursive index optimization",
    "The message queue system queued its own queue management messages",
    "The backend logging service logged its own logging configuration",
    "The API rate limiter rate-limited its own rate limiting rules",
    "The database connection pool achieved quantum connection multiplexing",
    "The backend security middleware encrypted its own encryption keys",
    "The service discovery system discovered its own service registry",
    "The transaction manager nested transactions within nested transactions",
    "The backend monitoring system monitored its own monitoring metrics",
    "The database migration system migrated its own migration history",
    "The event streaming platform streamed its own event definitions",
    "The backend caching strategy cached its own caching policies",
    "The API versioning system versioned its own version controllers",
    "The backend task scheduler scheduled its own scheduling tasks",
    "The database replication system replicated its own replication logs",
    "The backend authorization service authorized its own authorization rules",
    "The message serialization system serialized its own serializers",
    "The backend validation framework validated its own validators",
    "The error handling system handled its own error handlers",
    "The backend logging framework logged its own logging events",
    "The database query optimizer optimized its own optimization rules",
    "The backend health check system checked its own health status",
    "The API documentation system documented its own documentation",
    "The backend configuration service configured its own configurations",
    "The database backup system backed up its own backup history",
    "The backend testing framework tested its own test suites",
    "The service mesh proxy proxied its own proxy configurations",
    "The backend tracing system traced its own tracing spans",
    "The database partitioning strategy partitioned its own partitions",
    "The backend circuit breaker broke its own circuit logic",
    "The API response cache cached its own cache headers",
    "The backend job queue queued its own queue processors",
    "The database connection manager managed its own management connections",
    "The backend security scanner scanned its own security rules",
    "The API throttling system throttled its own throttle limits",
    "The backend metrics collector collected its own collection metrics",
    "The database deadlock detector detected its own detection patterns",
    "The backend session manager managed its own session states",
    "The API authentication service authenticated its own auth tokens",
    "The backend logging aggregator aggregated its own aggregation logs",
    "The database optimization engine optimized its own optimization strategies",
  ],
  devops: [
    "The kubernetes cluster orchestrated its own orchestration pods",
    "The CI/CD pipeline achieved recursive deployment automation",
    "The infrastructure as code terraformed its own terraform state",
    "The container registry containerized its own container images",
    "The service mesh achieved quantum network packet entanglement",
    "The chaos engineering system induced chaos in its own chaos tests",
    "The GitOps workflow git-synchronized its own synchronization state",
    "The automated scaling system scaled its own scaling metrics",
    "The continuous deployment system deployed its own deployment pipeline",
    "The container orchestration platform orchestrated its own orchestrators",
    "The infrastructure monitoring system monitored its own monitors",
    "The log aggregation service aggregated its own aggregation logs",
    "The deployment automation tool automated its own automation scripts",
    "The configuration management system managed its own management configs",
    "The secrets management service encrypted its own encryption keys",
    "The service discovery platform discovered its own discovery services",
    "The infrastructure provisioning tool provisioned its own provisioners",
    "The container networking system networked its own network policies",
    "The deployment rollback system rolled back its own rollback states",
    "The infrastructure security scanner scanned its own security rules",
    "The cluster management system managed its own management clusters",
    "The continuous integration system integrated its own integration tests",
    "The deployment strategy system strategized its own strategy patterns",
    "The infrastructure testing framework tested its own test infrastructure",
    "The container runtime system containerized its own runtime environment",
    "The deployment monitoring service monitored its own monitoring metrics",
    "The infrastructure backup system backed up its own backup infrastructure",
    "The service resilience system strengthened its own resilience patterns",
    "The deployment verification tool verified its own verification steps",
    "The infrastructure scaling system scaled its own scaling infrastructure",
    "The container orchestration system orchestrated its own orchestration logic",
    "The deployment pipeline system pipelined its own pipeline stages",
    "The infrastructure automation tool automated its own automation workflows",
    "The service mesh proxy proxied its own proxy configurations",
    "The deployment logging system logged its own logging infrastructure",
    "The container security system secured its own security containers",
    "The infrastructure monitoring platform monitored its own monitoring state",
    "The deployment health check system checked its own health status",
    "The container registry system registered its own registry services",
    "The infrastructure provisioning service provisioned its own provisioners",
    "The deployment configuration system configured its own configurations",
    "The container networking platform networked its own network services",
    "The infrastructure security platform secured its own security rules",
    "The deployment orchestration system orchestrated its own orchestrators",
    "The container monitoring service monitored its own monitoring metrics",
    "The infrastructure logging system logged its own logging state",
    "The deployment automation platform automated its own automation logic",
    "The container management system managed its own management containers",
    "The infrastructure testing service tested its own test environment",
    "The deployment security system secured its own security state",
  ],
  design: [
    "The design system recursively inherited from its own component library",
    "The user interface achieved quantum coherence with user expectations",
    "The design tokens system tokenized its own token definitions",
    "The atomic design structure achieved nuclear design fusion",
    "The responsive grid system transcended dimensional constraints",
    "The user experience flow mapped impossible user journeys",
    "The accessibility patterns achieved universal design singularity",
    "The visual hierarchy collapsed into a non-linear design space",
    "The interaction design model predicted its own user behaviors",
    "The design versioning system versioned its own version history",
    "The mockup generator automated its own design iterations",
    "The design component library composed its own composition rules",
    "The user interface pattern library patterned its own patterns",
    "The design collaboration tool collaborated with itself",
    "The prototyping system prototyped its own prototype flows",
    "The design asset manager managed its own management assets",
    "The interface animation system animated its own animation curves",
    "The design documentation system documented its own documentation",
    "The user testing framework tested its own test scenarios",
    "The design handoff system handed off its own handoff specs",
    "The interface accessibility checker checked its own accessibility",
    "The design system generator generated its own generation rules",
    "The user flow mapper mapped its own mapping logic",
    "The design token transformer transformed its own transformations",
    "The interface guidelines system guided its own guideline principles",
    "The design critique platform critiqued its own critique methods",
    "The user research system researched its own research methods",
    "The design versioning tool versioned its own version control",
    "The interface testing suite tested its own test coverage",
    "The design collaboration platform collaborated on its own collaborations",
    "The user journey mapper mapped its own journey patterns",
    "The design asset library cataloged its own catalog system",
    "The interface pattern matcher matched its own matching patterns",
    "The design specification tool specified its own specifications",
    "The user interaction logger logged its own logging patterns",
    "The design system explorer explored its own exploration paths",
    "The interface prototype builder built its own building blocks",
    "The design review system reviewed its own review process",
    "The user behavior analyzer analyzed its own analysis patterns",
    "The design component explorer explored its own exploration logic",
    "The interface accessibility mapper mapped its own mapping rules",
    "The design token manager managed its own management tokens",
    "The user flow validator validated its own validation rules",
    "The design system documenter documented its own documentation",
    "The interface pattern library organized its own organization",
    "The design asset organizer organized its own organization system",
    "The user testing platform tested its own testing methodology",
    "The design handoff automation automated its own automation rules",
    "The interface component builder built its own building system",
    "The design system validator validated its own validation patterns",
  ],
  management: [
    "The agile workflow achieved recursive sprint velocity optimization",
    "The project management system managed its own management metrics",
    "The sprint planning tool planned its own planning strategy",
    "The scrum framework scrummed its own scrum ceremonies",
    "The kanban board achieved quantum task state superposition",
    "The backlog prioritization system prioritized its own priorities",
    "The team velocity calculator calculated its own calculation metrics",
    "The project timeline estimated its own estimation accuracy",
    "The resource allocation system allocated its own allocation rules",
    "The stakeholder management platform managed its own management stakeholders",
    "The project risk assessment system assessed its own risk factors",
    "The sprint retrospective tool retrospected its own retrospectives",
    "The team capacity planning system planned its own planning capacity",
    "The project milestone tracker tracked its own tracking milestones",
    "The agile metrics dashboard dashboarded its own dashboard metrics",
    "The team collaboration platform collaborated with itself",
    "The project dependency mapper mapped its own mapping dependencies",
    "The sprint burndown chart burned down its own burndown metrics",
    "The team performance analyzer analyzed its own analysis metrics",
    "The project scope management system managed its own management scope",
    "The agile ceremony scheduler scheduled its own scheduling ceremonies",
    "The team communication platform communicated its own communications",
    "The project budget tracker tracked its own tracking budgets",
    "The sprint planning poker system pokered its own poker estimates",
    "The team workload balancer balanced its own balancing workloads",
    "The project status reporter reported its own reporting status",
    "The agile documentation system documented its own documentation",
    "The team feedback system feedback-looped its own feedback",
    "The project quality assurance system assured its own quality assurance",
    "The sprint goal setting tool set its own goal-setting goals",
    "The team resource scheduler scheduled its own scheduling resources",
    "The project timeline forecaster forecasted its own forecasting accuracy",
    "The agile team velocity predictor predicted its own prediction accuracy",
    "The team capacity calculator calculated its own calculation capacity",
    "The project risk matrix matrixed its own risk matrices",
    "The sprint backlog groomer groomed its own grooming backlogs",
    "The team performance evaluator evaluated its own evaluation metrics",
    "The project milestone planner planned its own planning milestones",
    "The agile reporting system reported its own reporting metrics",
    "The team workflow optimizer optimized its own optimization workflows",
    "The project resource allocator allocated its own allocation resources",
    "The sprint review system reviewed its own review process",
    "The team coordination platform coordinated its own coordination",
    "The project timeline simulator simulated its own simulation timelines",
    "The agile metrics collector collected its own collection metrics",
    "The team productivity analyzer analyzed its own analysis productivity",
    "The project scope validator validated its own validation scope",
    "The sprint velocity tracker tracked its own tracking velocity",
    "The team efficiency calculator calculated its own calculation efficiency",
    "The project risk mitigator mitigated its own mitigation risks",
  ],
  other: [
    "The quantum computing stack achieved recursive quantum entanglement",
    "The blockchain consensus mechanism achieved distributed truth singularity",
    "The augmented reality engine rendered impossible space-time geometries",
    "The artificial general intelligence system achieved recursive self-improvement",
    "The quantum cryptography system encrypted its own encryption keys",
    "The neural network architecture evolved its own evolution algorithms",
    "The distributed ledger technology validated its own validation chains",
    "The virtual reality environment simulated its own simulation physics",
    "The machine learning pipeline learned its own learning parameters",
    "The quantum error correction system corrected its own correction codes",
    "The blockchain smart contract contracted its own contract logic",
    "The augmented intelligence system augmented its own augmentation",
    "The quantum state analyzer analyzed its own analysis states",
    "The neural architecture search searched its own search space",
    "The distributed computing grid computed its own computation distribution",
    "The virtual environment renderer rendered its own rendering pipeline",
    "The machine reasoning system reasoned about its own reasoning logic",
    "The quantum optimization algorithm optimized its own optimization strategy",
    "The blockchain governance system governed its own governance rules",
    "The augmented perception system perceived its own perception patterns",
    "The quantum coherence maintainer maintained its own maintenance coherence",
    "The neural processing unit processed its own processing patterns",
    "The distributed consensus algorithm achieved consensus about consensus",
    "The virtual world generator generated its own generation rules",
    "The machine translation system translated its own translation models",
    "The quantum teleportation system teleported its own teleportation state",
    "The blockchain mining algorithm mined its own mining efficiency",
    "The augmented analytics system analyzed its own analytical methods",
    "The quantum memory system memorized its own memorization patterns",
    "The IoT sensor network sensed its own sensing thresholds",
    "The biometric authentication system authenticated its own authentication patterns",
    "The quantum randomness generator randomized its own random seeds",
    "The edge computing node computed its own computational boundaries",
    "The autonomous system framework automated its own automation rules",
    "The quantum information processor processed its own processing qubits",
    "The holographic storage system holographed its own storage holograms",
    "The metamaterial compiler compiled its own material properties",
    "The cognitive computing engine cognized its own cognition patterns",
    "The quantum annealing system annealed its own annealing schedule",
    "The bio-digital interface interfaced with its own interface protocols",
    "The quantum supremacy test proved its own supremacy criteria",
    "The neural cryptography system encrypted its own encryption patterns",
    "The molecular computing platform computed its own molecular states",
    "The quantum sensor array sensed its own sensing capabilities",
    "The swarm intelligence system swarmed its own swarm algorithms",
    "The quantum communication channel communicated its own channel status",
    "The brain-computer interface interfaced its own interface signals",
    "The quantum machine learning system learned its own learning quantum states",
  ],
  general: [
    "The distributed quantum blockchain achieved recursive cryptographic consensus in the neural mesh network",
    "The hyper-converged infrastructure stack recursively optimized its own optimization algorithms through quantum machine learning",
    "The zero-trust quantum-resistant blockchain validated its own validation protocols in the distributed edge network",
    "The neural-enhanced microservices mesh achieved quantum entanglement with the distributed ledger consensus",
    "The self-healing infrastructure recursively automated its own automation workflows through quantum computing",
    "The quantum-secure hybrid cloud orchestrated its own orchestration layers in the distributed mesh",
    "The blockchain-enabled quantum neural network encrypted its own encryption algorithms through recursive learning",
    "The distributed quantum computing platform achieved coherence with its own coherence protocols",
    "The neural-enhanced containerization system containerized its own container orchestration through quantum optimization",
    "The quantum-resistant zero-knowledge proof system proved its own proof verification in the distributed ledger",
    "The hybrid quantum-classical computing stack optimized its own optimization metrics through recursive neural networks",
    "The distributed quantum cryptography system encrypted its own encryption keys through blockchain consensus",
    "The neural-quantum hybrid architecture achieved sentience in its own sentience verification protocols",
    "The quantum-secure microservices mesh orchestrated its own orchestration patterns through neural optimization",
    "The blockchain-enabled quantum computing platform computed its own computation verification through distributed consensus",
    "The neural-enhanced quantum cryptography system achieved quantum supremacy in its own supremacy verification layer",
    "The quantum-enabled artificial general intelligence recursively optimized its own optimization neural networks",
    "The distributed quantum-resistant blockchain achieved consensus about its own consensus mechanisms",
    "The neural-quantum hybrid microservices mesh synchronized its own synchronization protocols",
    "The quantum-secure edge computing platform edge-processed its own edge processing algorithms",
    "The blockchain-powered quantum neural network deep-learned its own deep learning architectures",
    "The quantum-entangled distributed system validated its own validation quantum states",
    "The neural-enhanced zero-trust architecture zero-trusted its own trust verification protocols",
    "The quantum-resistant hybrid cloud platform cloud-computed its own computation matrices",
    "The blockchain-secured quantum mesh network mesh-networked its own networking protocols",
    "The neural-quantum cryptographic system cryptographically secured its own security algorithms",
    "The distributed quantum-enabled platform containerized its own container orchestration layers",
    "The quantum-neural hybrid architecture self-healed its own healing mechanisms",
    "The blockchain-enhanced quantum computing grid grid-computed its own computation verification",
    "The neural-secure quantum cryptography engine cryptographically enhanced its own enhancement protocols",
    "The quantum-resistant distributed ledger consensus-validated its own validation chains",
    "The neural-quantum hybrid mesh achieved hyperconvergence with its own convergence patterns",
    "The quantum-enabled blockchain platform chain-validated its own validation quantum states",
    "The distributed neural-quantum system recursively optimized its own optimization matrices",
    "The quantum-secure hybrid architecture architected its own architectural patterns",
    "The blockchain-powered quantum platform quantum-processed its own processing states",
    "The neural-enhanced distributed system distributed its own distribution protocols",
    "The quantum-resistant zero-knowledge proof system proved its own proof verification chains",
    "The hybrid quantum-classical computing stack stack-computed its own computation layers",
    "The blockchain-secured quantum mesh mesh-secured its own security protocols",
    "The neural-quantum cryptographic engine crypto-secured its own security matrices",
    "The distributed quantum platform platform-validated its own validation states",
    "The quantum-neural hybrid system system-optimized its own optimization patterns",
    "The blockchain-enhanced quantum grid grid-validated its own validation protocols",
    "The neural-secure quantum engine engine-processed its own processing matrices",
    "The quantum-resistant distributed platform platform-secured its own security chains",
    "The neural-quantum hybrid architecture architecture-validated its own validation patterns",
    "The quantum-enabled blockchain system system-secured its own security states",
    "The distributed neural-quantum platform platform-optimized its own optimization protocols",
  ],
};
